name: Build

on:
  pull_request:
    branches: [ "main" ]

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: ${{ matrix.os }} - ${{ matrix.config }}
    runs-on: ${{ matrix.config }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        config: [ Debug, Release ]

    env:
      CCACHE_DIR: ${{ github.workspace }}/.ccache
      CCACHE_MAXSIZE: 500M
      CCACHE_COMPRESS: "true"

      VCPKG_BINARY_SOURCES: "clear;files,${{ github.workspace }}/.vcpkg_cache,readwrite"
      VCPKG_DISABLE_METRICS: "1"

    steps:
    - name: Checkout the Repository
      uses: actions/checkout@v6 # v6

    - name: Install CMake and Ninja
      uses: lukka/get-cmake@f176ccd3f28bda569c43aae4894f06b2435a3375 # v4.2.3
      with:
        cmakeVersion: 3.31.10
        ninjaVersion: 1.11.1

    - name: Cache ccache
      uses: actions/cache@v5
      with:
        path: .ccache
        key: ccache-${{ runner.os }}-${{ matrix.config }}-${{ hashFiles('CMakeLists.txt', '**/CMakeLists.txt', 'vcpkg.json', 'vcpkg-configuration.json', 'CMakePresets.json') }}
        restore-keys: |
          ccache-${{ runner.os }}-${{ matrix.config }}-
          ccache-${{ runner.os }}-

    - name: Cache vcpkg
      uses: actions/cache@v5
      with:
        path: |
          .vcpkg_cache
          ~/.cache/vcpkg
          ~/Library/Caches/vcpkg
          %LOCALAPPDATA%\vcpkg\archives
        key: vcpkg-${{ runner.os }}-${{ hashFiles('vcpkg.json', 'vcpkg-configuration.json', 'vcpkg-lock.json') }}
        restore-keys: |
          vcpkg-${{ runner.os }}-

    - name: Setup vcpkg
      uses: lukka/run-vcpkg@5e0cab206a5ea620130caf672fce3e4a6b5666a1 # v11.5
      with:
        vcpkgDirectory: ${{ github.workspace }}/vcpkg

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1-mesa-dev libglu1-mesa-dev xorg-dev xvfb

    - name: Configure CMake
      run: >
        cmake -S . -B build/${{ matrix.os }}/${{ matrix.config }}
        -G Ninja
        -DCMAKE_BUILD_TYPE=${{ matrix.config }}
        -DCMAKE_C_COMPILER_LAUNCHER=ccache
        -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
        -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
        -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake

    - name: Build
      run: cmake --build build/${{ matrix.os }}/${{ matrix.config }} --config ${{ matrix.config }}

    - name: Test
      run: ctest --test-dir build/${{ matrix.os }}/${{ matrix.config }} --output-on-failure
