name: coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y lcov libgl1-mesa-dev libglu1-mesa-dev xorg-dev xvfb

    - name: Install CMake and Ninja
      uses: lukka/get-cmake@latest
      with:
        cmakeVersion: 3.31.10
        ninjaVersion: 1.11.1

    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11

    - name: Configure + Build
      uses: lukka/run-cmake@v10
      with:
        configurePreset: code-coverage
        buildPreset: code-coverage

    - name: Run Tests
      run: |
        xvfb-run -a ctest --preset test-coverage

    - name: Analyze test data
      run: ./scripts/analyze_coverage.sh

    - name: Upload coverage to Codacy
      run: |
        bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r ./build/code-coverage/coverage-data/coverage.filtered.info
      env:
        CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
