name: coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y lcov ninja-build libgl1-mesa-dev libglu1-mesa-dev xorg-dev

    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11

    - name: Install vcpkg Dependencies
      run: vcpkg install

    - name: Configure + Build
      uses: lukka/run-cmake@v10
      with:
        configurePreset: code-coverage
        buildPreset: code-coverage

    - name: Run Tests
      run: ctest --preset test-coverage
      env:
        LSAN_OPTIONS: suppressions=${{ github.workspace }}/asan.supp
        ASAN_OPTIONS: suppressions=${{ github.workspace }}/asan.supp

    - name: Analyze test data
      run: ./scripts/analyze_coverage.sh

    - name: Debug vcpkg + CMake
      run: |
        echo "VCPKG_ROOT=$VCPKG_ROOT"
        echo "VCPKG_OVERLAY_PORTS=$VCPKG_OVERLAY_PORTS"
        cmake --version
        find . -maxdepth 3 -type d -name "vcpkg-ports" -print

    - name: Upload converage to Codacy
      run: |
        bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r ./build/code-coverage/coverage-data/coverage.filtered.info
      env:
        CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}

    - name: Publish Badge JSON
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git fetch origin badges || git checkout --orphan badges
        git checkout badges
        cp -f ./build/code-coverage/coverage-report/coverage-badge.json ./.github/badges/coverage-badge.json
        git add ./.github/badges/coverage-badge.json
        git commit -m "Update coverage badge" || echo "No changes"
        git push origin badges --force

